name: iOS Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode Project
        run: xcodegen generate

      - name: Resolve Package Dependencies
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          xcodebuild -resolvePackageDependencies \
            -project GrillaFux.xcodeproj \
            -scheme GrillaFux

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.P12_BASE64 }}
          p12-password: ${{ secrets.P12_PASSWORD }}

      - name: Install Provisioning Profile
        run: |
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          echo "${{ secrets.MOBILEPROVISION_BASE64 }}" | base64 --decode > \
          "$HOME/Library/MobileDevice/Provisioning Profiles/GrillaFux_Distribution.mobileprovision"

      - name: Build iOS App (Archive Signed V18)
        run: |
          # No necesitamos -xcconfig porque ya est√° en el project.yml
          xcodebuild \
            -project GrillaFux.xcodeproj \
            -scheme GrillaFux \
            -sdk iphoneos \
            -configuration Release \
            -archivePath "$PWD/build/GrillaFux.xcarchive" \
            DEVELOPMENT_TEAM=ZY8K4XH28N \
            CODE_SIGN_STYLE=Automatic \
            clean archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath "$PWD/build/GrillaFux.xcarchive" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$PWD/build/output"

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: GrillaFux.ipa
          path: build/output/*.ipa
